In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from sklearn import preprocessing
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
# Load Text Cleaning Pkgs
!pip install neattext
import neattext as nfx

     |████████████████████████████████| 114 kB 4.5 MB/s 


In [ ]:
# Load ML Pkgs
# Estimators
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

# Transformers
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/emoji/tweet_emotions.csv')

In [ ]:
data

tweet_id   sentiment  \
0      1956967341       empty   
1      1956967666     sadness   
2      1956967696     sadness   
3      1956967789  enthusiasm   
4      1956968416     neutral   
...           ...         ...   
39995  1753918954     neutral   
39996  1753919001        love   
39997  1753919005        love   
39998  1753919043   happiness   
39999  1753919049        love   

                                                 content  
0      @tiffanylue i know  i was listenin to bad habi...  
1      Layin n bed with a headache  ughhhh...waitin o...  
2                    Funeral ceremony...gloomy friday...  
3                   wants to hang out with friends SOON!  
4      @dannycastillo We want to trade with someone w...  
...                                                  ...  
39995                                   @JohnLloydTaylor  
39996                     Happy Mothers Day  All my love  
39997  Happy Mother's Day to all the mommies out ther...  
39998  @niariley WASSUP BEAUTIFUL!!! FOLLOW ME!!  PEE...  
39999  @mopedronin bullet train from tokyo    the gf ...  

[40000 rows x 3 columns]

In [ ]:
# User handles
data['Clean_Text'] = data['content'].apply(nfx.remove_userhandles)
# Stopwords
data['Clean_Text'] = data['Clean_Text'].apply(nfx.remove_stopwords)
#Hashtags
data['Clean_Text'] = data['Clean_Text'].apply(nfx.remove_hashtags)

In [ ]:
data

tweet_id   sentiment  \
0      1956967341       empty   
1      1956967666     sadness   
2      1956967696     sadness   
3      1956967789  enthusiasm   
4      1956968416     neutral   
...           ...         ...   
39995  1753918954     neutral   
39996  1753919001        love   
39997  1753919005        love   
39998  1753919043   happiness   
39999  1753919049        love   

                                                 content  \
0      @tiffanylue i know  i was listenin to bad habi...   
1      Layin n bed with a headache  ughhhh...waitin o...   
2                    Funeral ceremony...gloomy friday...   
3                   wants to hang out with friends SOON!   
4      @dannycastillo We want to trade with someone w...   
...                                                  ...   
39995                                   @JohnLloydTaylor   
39996                     Happy Mothers Day  All my love   
39997  Happy Mother's Day to all the mommies out ther...   
39998  @niariley WASSUP BEAUTIFUL!!! FOLLOW ME!!  PEE...   
39999  @mopedronin bullet train from tokyo    the gf ...   

                                              Clean_Text  
0      know listenin bad habit earlier started freaki...  
1           Layin n bed headache ughhhh...waitin call...  
2                    Funeral ceremony...gloomy friday...  
3                               wants hang friends SOON!  
4                      want trade Houston tickets, will.  
...                                                  ...  
39995                                                     
39996                             Happy Mothers Day love  
39997  Happy Mother's Day mommies there, woman man lo...  
39998  WASSUP BEAUTIFUL!!! FOLLOW ME!! PEEP NEW HIT S...  
39999  bullet train tokyo gf visiting japan thursday ...  

[40000 rows x 4 columns]

In [ ]:
# Features & Labels
Xfeatures = data['Clean_Text']
ylabels = data['sentiment']

In [ ]:
#  Split Data
x_train,x_test,y_train,y_test = train_test_split(Xfeatures,ylabels,test_size=0.3,random_state=42)

In [ ]:
x_train

38015    Hehe option (advertising) world mess! future! ...
2281     woke day need work sucks. dentist filling 12 s...
36629                                                  u u
6087                             leave forever! We'll miss
11792    LT training today, ehhh hard tall hard was. fe...
                               ...                        
6265                                              Cleaning
11284               ooo goddddd; vodafone trouble. network
38158           watching run fat boy run...haha soo funny.
860      pork products can, they've fucking stopped imp...
15795    Bill, likewise pleasure- time spend time talki...
Name: Clean_Text, Length: 28000, dtype: object

In [ ]:
x=data['content']
y=data['sentiment']

In [ ]:
lb = preprocessing.LabelBinarizer()

In [ ]:
lb.fit(y_train)

LabelBinarizer()

In [ ]:
lb.classes_

array(['anger', 'boredom', 'empty', 'enthusiasm', 'fun', 'happiness',
       'hate', 'love', 'neutral', 'relief', 'sadness', 'surprise',
       'worry'], dtype='<U10')

In [ ]:
y_test=lb.transform(y_test)
y_train=lb.transform(y_train)

In [ ]:
y_train=np.array(y_train)

In [ ]:
y_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 0]])

In [ ]:
print(x_train[0])

know listenin bad habit earlier started freakin =[


In [ ]:
tokenizer=Tokenizer(num_words=50000,oov_token="<OOV>")
tokenizer.fit_on_texts(Xfeatures)
word_index=tokenizer.word_index
print(word_index)

{'<OOV>': 1, "i'm": 2, 'day': 3, 'good': 4, 'like': 5, 'quot': 6, 'http': 7, 'today': 8, 'work': 9, 'love': 10, 'got': 11, 'going': 12, 'happy': 13, 'lol': 14, 'time': 15, 'u': 16, 'know': 17, 'com': 18, 'im': 19, 'amp': 20, "can't": 21, 'it': 22, 'night': 23, 'new': 24, 'home': 25, 'think': 26, 'thanks': 27, 'want': 28, '2': 29, 'oh': 30, 'you': 31, 'me': 32, 'miss': 33, 'great': 34, 'need': 35, 'morning': 36, 'hope': 37, 'haha': 38, 'twitter': 39, 'feel': 40, 'fun': 41, '3': 42, 'now': 43, 'sad': 44, 'wish': 45, 'tomorrow': 46, 'sorry': 47, 'tonight': 48, 'bad': 49, 'right': 50, 'i': 51, "i'll": 52, 'nice': 53, 'better': 54, 'gonna': 55, 'yeah': 56, 'sleep': 57, "that's": 58, 'week': 59, 'way': 60, 'getting': 61, 'weekend': 62, 'mothers': 63, 'come': 64, "mother's": 65, 'bit': 66, 'bed': 67, 'people': 68, 'twitpic': 69, "i've": 70, 'too': 71, 'school': 72, 'dont': 73, 'watching': 74, 'lt': 75, 'awesome': 76, 'days': 77, 'wait': 78, 'hate': 79, 'hey': 80, 'best': 81, 'yes': 82, '4': 8

In [ ]:
len(word_index)

32888

In [ ]:
x_train=tokenizer.texts_to_sequences(x_train)
x_test=tokenizer.texts_to_sequences(x_test)

In [ ]:
x_train=pad_sequences(x_train,padding='post')
x_test=pad_sequences(x_test,padding='post',maxlen=36)

In [ ]:
print(x_train.shape)
print(x_test.shape)

(28000, 36)
(12000, 36)


In [ ]:
x_train[0]

array([  378,  2435,  6005,   184,  1222,  1033,   281,    15,    82,
       31755, 31756,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0],
      dtype=int32)

In [ ]:
vs=33207
ed=64
model=tf.keras.Sequential([
    tf.keras.layers.Embedding(vs,50),
    # tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.LSTM(256,return_sequences=True),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(256,return_sequences=True)),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(256)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(13,activation='softmax')
])
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
num_epochs=10
history=model.fit(x_train,y_train,epochs=num_epochs,validation_data=(x_test,y_test),verbose=1)

Epoch 1/10
875/875 [==============================] - 21s 24ms/step - loss: 2.0219 - accuracy: 0.2880 - val_loss: 1.9551 - val_accuracy: 0.3293
Epoch 2/10
875/875 [==============================] - 18s 20ms/step - loss: 1.8247 - accuracy: 0.3816 - val_loss: 1.9723 - val_accuracy: 0.3288
Epoch 3/10
875/875 [==============================] - 18s 20ms/step - loss: 1.6320 - accuracy: 0.4488 - val_loss: 2.0852 - val_accuracy: 0.3292
Epoch 4/10
875/875 [==============================] - 18s 20ms/step - loss: 1.4409 - accuracy: 0.5245 - val_loss: 2.1566 - val_accuracy: 0.3150
Epoch 5/10
875/875 [==============================] - 21s 24ms/step - loss: 1.2360 - accuracy: 0.5987 - val_loss: 2.3716 - val_accuracy: 0.2895
Epoch 6/10
875/875 [==============================] - 19s 22ms/step - loss: 1.0391 - accuracy: 0.6648 - val_loss: 2.5517 - val_accuracy: 0.2837
Epoch 7/10
875/875 [==============================] - 18s 21ms/step - loss: 0.8719 - accuracy: 0.7180 - val_loss: 2.8822 - val_accuracy:

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
pred

array([[3.4293259e-04, 1.3961304e-03, 5.9739847e-02, ..., 1.4166275e-02,
        3.0250711e-02, 6.3494422e-02],
       [1.4929510e-09, 1.6653167e-09, 2.5805235e-03, ..., 1.7202989e-04,
        2.6537999e-04, 8.3648285e-04],
       [2.3035889e-07, 2.3304173e-08, 3.3330801e-07, ..., 1.6746148e-04,
        1.7957282e-05, 9.9973029e-01],
       ...,
       [5.6413689e-04, 8.1263564e-04, 2.7657518e-02, ..., 7.0327677e-02,
        6.7372844e-02, 1.8474264e-01],
       [2.1349400e-08, 2.6925754e-08, 5.3000525e-03, ..., 1.3805499e-03,
        6.3877011e-04, 4.6494063e-03],
       [4.2129384e-04, 3.2707129e-04, 1.0951547e-03, ..., 5.2749419e-01,
        3.0376442e-02, 2.9013613e-01]], dtype=float32)

In [ ]:
pred=model.predict(x_test)
x=0
i=0
for arr in pred:
    # print(np.argmax(arr),np.argmax(y_test[i]))
    x=x+(np.argmax(arr)==np.argmax(y_test[i]))
    i=i+1
print("Score",x/len(y_test)*100)

Score 25.758333333333333


Score 25.758333333333333
